In [1]:
import numpy as np

In [4]:
my_array = np.array([1, 10, -5, 20])
my_array

array([ 1, 10, -5, 20])

In [8]:
print(f"The mean is {my_array.mean()}")
print(f"The mean is {my_array.std()}")

The mean is 6.5
The mean is 9.447221813845593


In [10]:
print(f"Multiplication by 2: {my_array*2}")

Multiplication by 2: [  2  20 -10  40]


In [11]:
my_arr_4x3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
my_arr_4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
print(f"Inverted matrix:\n{my_arr_4x3.T}")

Inverted matrix:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [21]:
print(f"elements in this matrix: {my_arr_4x3.size}")

elements in this matrix: 12


In [23]:
print(f"shape of  this matrix: {my_arr_4x3.shape}")

shape of  this matrix: (4, 3)


In [49]:
random_integers = np.random.randint(100,200, 20)
random_integers

array([121, 182, 125, 118, 130, 137, 149, 181, 152, 119, 161, 181, 134,
       111, 180, 151, 162, 153, 130, 123], dtype=int32)

In [53]:
random_integers % 2

array([1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1],
      dtype=int32)

In [56]:
even_numbers = random_integers[random_integers % 2 == 0]
even_numbers

array([182, 118, 130, 152, 134, 180, 162, 130], dtype=int32)

In [58]:
sliced_array = even_numbers[2:8]
sliced_array

array([130, 152, 134, 180, 162, 130], dtype=int32)

In [68]:
arr1 = np.random.randint(0,10,4)
arr2 = np.random.randint(0,10,4)

print(f"The two arrays are:\n{arr1}\n{arr2}")

The two arrays are:
[3 3 4 1]
[0 4 2 4]


In [69]:
print(f"The sum of the two arrays is {arr1+arr2}")
print(f"The difference of the two arrays is {arr1-arr2}")
print(f"The multiplication of the two arrays is {arr1*arr2}")

The sum of the two arrays is [3 7 6 5]
The difference of the two arrays is [ 3 -1  2 -3]
The multiplication of the two arrays is [ 0 12  8  4]


In [71]:
np.dot(arr1, arr2)

np.int32(24)

In [73]:
(arr1*arr2).sum()

np.int64(24)